version: '3'

services:
  server:
    build:
      context: ./Chat_Room/server
    ports:
      - "5000:5000"  # Adjust port as needed
    volumes:
      - ./server:/app

  client:
    build:
      context: ./Chat_Room/client
    volumes:
      - ./client:/app
